onlinejudge/anarchygolf.py
onlinejudge/aoj.py
onlinejudge/atcoder.py
onlinejudge/codeforces.py
onlinejudge/hackerrank.py
onlinejudge/yukicoder.py

https://github.com/kmyk/online-judge-tools/issues/16

improve url parsers

---

onlinejudge/atcoder.py

#23 
次を直した
-   キーワード引数が未定義でエラー
-   そもそもAtCoderでは提出の詳細ページへのURLが通知されてこない

fix the problem of submission to AtCoder

---

onlinejudge/implementation/command/submit.py

add an error message for submit subcommand

---

onlinejudge/aoj.py
onlinejudge/implementation/command/download.py
onlinejudge/implementation/command/login.py
onlinejudge/implementation/main.py
onlinejudge/yukicoder.py
tests/main.py

Download system testcases

---

onlinejudge/yukicoder.py

use HTTPS for yukicoder at all

---

onlinejudge/implementation/command/test.py

terminate the zombie processes after TLE

---

onlinejudge/__init__.py
onlinejudge/csacademy.py
onlinejudge/implementation/main.py
readme.md

CS Academy support

---

onlinejudge/atcoder.py
tests/main.py

recognize beta.atcoder.jp

---

onlinejudge/anarchygolf.py
onlinejudge/aoj.py
onlinejudge/atcoder.py
onlinejudge/codeforces.py
onlinejudge/csacademy.py
onlinejudge/hackerrank.py
onlinejudge/implementation/command/download.py
onlinejudge/implementation/command/generate_scanner.py
onlinejudge/implementation/command/login.py
onlinejudge/implementation/command/submit.py
onlinejudge/implementation/utils.py
onlinejudge/implementation/version.py
onlinejudge/yukicoder.py
setup.py

add a remark to the User-Agent

---

onlinejudge/anarchygolf.py
onlinejudge/aoj.py
onlinejudge/atcoder.py
onlinejudge/codeforces.py
onlinejudge/csacademy.py
onlinejudge/hackerrank.py
onlinejudge/implementation/command/download.py
onlinejudge/implementation/utils.py
onlinejudge/problem.py
onlinejudge/yukicoder.py

Refactoring

---

onlinejudge/implementation/command/generate_scanner.py
tests/download.py
tests/generate_scanner.py

generate-scanner の改善

---

onlinejudge/__init__.py
onlinejudge/implementation/command/login.py
onlinejudge/implementation/command/submit.py
onlinejudge/implementation/main.py
onlinejudge/implementation/utils.py
onlinejudge/topcoder.py
setup.py

TopCoderへのsubmitに対応

---

onlinejudge/yukicoder.py
tests/yukicoder.py

#93: add YukicoderService().get_problems

---

setup.py

Windows上のCIも足しておきたかったがTravis CIだとだめだったのでしない

#101: specify the encoding of a file at setup.py

---

tests/code_statistics.py

#59: code-statistics: add tests

---

onlinejudge/implementation/main.py
readme.md

#59: code-statistics: update readme

---

onlinejudge/atcoder.py

#138: submit: AtCoder: print an err msg if not logged in

---

onlinejudge/implementation/command/split_input.py

 #152: add newline for --header option

---

onlinejudge/implementation/command/split_input.py
onlinejudge/implementation/command/test.py
onlinejudge/implementation/command/test_reactive.py
onlinejudge/implementation/main.py

#154: --shell by default

---

onlinejudge/implementation/command/test.py

#153: use 1-based for lineno of "-1" option

---

onlinejudge/implementation/command/get_standings.py
onlinejudge/implementation/main.py
onlinejudge/problem.py
onlinejudge/topcoder.py

#58: add new subcommand: get-standings

---

onlinejudge/atcoder.py

#162: fix a bug of login subcommand for beta.atcoder.jp

---

onlinejudge/implementation/version.py

 RELEASE: 0.1.33

---

onlinejudge/implementation/main.py

fix reactive typo

---

.travis.yml
onlinejudge/anarchygolf.py
onlinejudge/aoj.py
onlinejudge/atcoder.py
onlinejudge/codeforces.py
onlinejudge/csacademy.py
onlinejudge/dispatch.py
onlinejudge/hackerrank.py
onlinejudge/implementation/command/download.py
onlinejudge/implementation/command/utils.py
onlinejudge/implementation/logging.py
onlinejudge/implementation/main.py
onlinejudge/implementation/utils.py
onlinejudge/problem.py
onlinejudge/service.py
onlinejudge/submission.py
onlinejudge/topcoder.py
onlinejudge/yukicoder.py

#183: add type hints

---

.travis.yml
onlinejudge/implementation/version.py

RELEASE: 0.1.48

---

onlinejudge/implementation/main.py

Add tle help message

---

oj
onlinejudge/__about__.py
onlinejudge/dispatch.py
onlinejudge/implementation/command/code_statistics.py
onlinejudge/implementation/command/download.py
onlinejudge/implementation/command/generate_output.py
onlinejudge/implementation/command/generate_scanner.py
onlinejudge/implementation/command/get_standings.py
onlinejudge/implementation/command/login.py
onlinejudge/implementation/command/split_input.py
onlinejudge/implementation/command/submit.py
onlinejudge/implementation/command/test.py
onlinejudge/implementation/command/test_reactive.py
onlinejudge/implementation/download_history.py
onlinejudge/implementation/format_utils.py
onlinejudge/implementation/logging.py
onlinejudge/implementation/main.py
onlinejudge/implementation/utils.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/topcoder.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py

black は勢いがありすぎたので諦めて yapf にしました。
それでも丸ごと変換すると確認が厳しいので autopep8 で刻んで変換しました。
@fukatani 動いてるはずなので軽くでいいですが、念のため確認お願いします。よさそうならマージボタン押してください。

#243 run formatters (yapf + isort)

---

tests/command_download_atcoder.py

Resolve #273 fix test name

---

tests/command_test.py

#258: add a test case for #256

---

onlinejudge/__init__.py
onlinejudge/implementation/main.py
tests/command_version.py

Resolve #265 #266
PR分けたほうがいいかしら？

Add --version option and __version__ accessible as onlinejudge.__version__

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 0.1.53

---

LOGIN_WITH_COOKIES.md
readme.md

Add introduction login method.

---

onlinejudge/implementation/main.py
onlinejudge/implementation/utils.py
onlinejudge/service/yukicoder.py
tests/command_download_yukicoder.py
tests/command_submit.py
tests/continuous_integration.py

#275 add the submit feature for yukicoder

---

LOGIN_WITH_COOKIES.md
onlinejudge/implementation/command/login.py
onlinejudge/implementation/main.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py
tests/command_login.py

close #200
-   [x] #287 の後にrebaseしてからmerge (#287 とは独立だが衝突するので)
-   [x] テストを書く

#200 add --check option to login command

---

setup.py

#290: add setuptools>=30.0.8 to setup.py for setup.cfg

---

readme.md

#275: fix readme.md

---

onlinejudge/implementation/main.py
onlinejudge/service/__init__.py
onlinejudge/service/poj.py
readme.md
tests/command_download_others.py

#113: support POJ

---

CHANGELOG.md
onlinejudge/__about__.py

we already add enough number of features, so it's about time to bump the version

RELEASE: 0.1.54

---

onlinejudge/implementation/main.py
onlinejudge/service/__init__.py
onlinejudge/service/kattis.py
readme.md
tests/command_download_kattis.py

#305: support download from Kattis

---

tests/service_codeforces.py

簡単にですがテストを足します
とりあえずまずファイルだけ作っておくという側面が強い

#318: add unit tests for Codeforces

---

onlinejudge/implementation/utils.py
onlinejudge/service/atcoder.py
tests/service_atcoder.py

AtCoder の提出結果をいじる機能です
冗長な繰り返しとそれに起因するバグを避けるために技巧的なことをしています

 #318: add a feature to get detailed information of submissions

---

onlinejudge/dispatch.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/hackerrank.py
onlinejudge/service/kattis.py
onlinejudge/service/poj.py
onlinejudge/service/topcoder.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py

引数名はドキュメントの一部なのでその修正もしていますが、互換性の問題は発生しないはずです

add docstrings

---

onlinejudge/service/codeforces.py
onlinejudge/service/toph.py
onlinejudge/type.py

these make code simple and safe

remove "if TYPE_CHECKING:" guard and remove quotations from  'requests.Session' 

---

onlinejudge/_implementation/main.py
onlinejudge/service/topcoder.py
readme.md

-   Topcoder uses sometims TopCoder, but it seems Topcoder is correct now.
-   yukicoder is better than Yukicoder

fix names of services

---

docs/onlinejudge.service.rst
docs/onlinejudge.service.toph.rst

#302: add Toph to the API documents

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/command/login.py
onlinejudge/_implementation/command/submit.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/hackerrank.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py

通常は発生しない状態という意味での例外ではないので真偽値とかで返してもいいですが、事象の性質的に例外として投げた方が呼び出し側も楽なはずです

#318: add `LoginError`, `SubmissionError` and `NotLoggedInError` exeptions

---

onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py

せめてAPIドキュメントだけはまともにします。汚ないのは問題そのものの難しさなので許してください

NONE: update utils.getter_with_load_details to take a type as an argument

---

onlinejudge/_implementation/command/submit.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/hackerrank.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py

提出周りのinterfaceの改善です。特に、 language と language id の区別が分かるようにします。

#318: improve the interface around submission

---

onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/topcoder.py
onlinejudge/service/yukicoder.py

#318: add links to official APIs

---

onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/hackerrank.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py

#318: hide utility sub-classes of `Submission`

---

onlinejudge/_implementation/utils.py
onlinejudge/service/codeforces.py
onlinejudge/service/hackerrank.py
onlinejudge/service/yukicoder.py

頻出パターンになってたのでutility側に吸収させました。

NONE: print URL if redirected

---

onlinejudge/_implementation/utils.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/hackerrank.py
onlinejudge/service/kattis.py
onlinejudge/service/poj.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py
tests/service_atcoder.py
tests/service_codeforces.py

必要ないわりに互換性の問題を生む可能性があるので消しました。

#318: stop using the singleton pattern since it is not required

---

tests/service_atcoder.py
tests/service_codeforces.py
tests/service_yukicoder.py

いくつか修正せずそのままのものがありますが、これは見やすさのための意図的なものです。

#351: use self.assertIsNone

---

.travis.yml

CIをするとAtCoderなどの鯖へ通信が発生してしまうので、これを減らしたくて実行に制限をかけてました。でもちゃんとレビューをしてもらえるようになって #356 みたいなことをしたさがでてきたので、これを消したいです。
(@fukatani 以前にここを消すコミットが来たときに reject してしまった記憶がありますが、あれは失敗でした。ごめんなさい :bow: )

NONE: enable CI on all branches

---

.travis.yml
onlinejudge/_implementation/utils.py

close #363 
@fukatani 手元では動作確認できていませんが、たぶん修正されているはずです

#363: fix the error on Python 3.5.2

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

#318: add the feature to iterate submissions of AtCoder

---

onlinejudge/service/atcoder.py

とりあえず注意を書きます。
いくつかmethod名の検討が終わってないからです。
https://online-judge-tools.readthedocs.io/en/master/onlinejudge.service.atcoder.html#onlinejudge.service.atcoder.AtCoderProblem.get_task_name

#318: add a note for the specification of the onlinejudge.service.atcoder module

---

onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/hackerrank.py
onlinejudge/service/kattis.py
onlinejudge/service/poj.py
onlinejudge/service/topcoder.py
onlinejudge/type.py

妙な文字列を返しても混乱させるだけだし、本当にほしいのはもっと表示用の名前のはずなので

#375: change the return values of Service.get_name()

---

onlinejudge/service/atcoder.py
onlinejudge/type.py
tests/service_atcoder.py

-  `AtCoderProblem.get_task_name()` を `Problem.get_name()` を作って置き換え
-  `AtCoderContest.get_contest_name()` を `AtCoderContest.get_name()` で置き換え

 #375: rename two methods to get_name()

---

readme.md

close #374 
#383 の後にmergeしてください
ライブラリのドキュメントのリンクや用例を書きました
(これが入ったらバージョンを上げる予定です)

#374: update readme.md

---

readme.md

#274: list names of contributors

---

onlinejudge/service/atcoder.py

次でエラーが起きていました
https://github.com/kmyk/online-judge-tools/blob/ad8b35d724c4599e97443db36de3760c14ddeac4/onlinejudge/service/atcoder.py#L244-L249

NONE: fix AtCoderContest._load_details

---

onlinejudge/__about__.py

#384 #386 #387 がマージされたらこれもマージしてください

RELEASE: 6.0.0

---

CHANGELOG.md
readme.md

NONE: update CHANGELOG.md

---

onlinejudge/service/atcoder.py

close #391 
修正です。非ログイン状態だと `Submit` `提出` みたいな列が現われず、これによりエラーになっていました。
(`提出` がなかったのも同時に直してしまいました。すこし行儀が悪いかも？)

#391: fix a bug of `AtCoderContest.list_problems()`

---

onlinejudge/service/codeforces.py
tests/service_codeforces.py

close #370 
-   次を仮定してたのを修正した関係で、同時に他のコーナーケースにも対応しています。
https://github.com/kmyk/online-judge-tools/blob/5d224d441fc90797d83f418854ca4b26816b8aa5/onlinejudge/service/codeforces.py#L88

#370: fix bugs around the indices of problems at Codeforces

---

onlinejudge/service/aoj.py
tests/command_download_aoj.py
tests/service_aoj.py

close #371 
やりました。
Arenaの問題は `arena_id` + `alphabet` という形で存在するため、新しく class を切りました。

#371: support AOJ Arena

---

CHANGELOG.md
onlinejudge/__about__.py
onlinejudge/_implementation/main.py
onlinejudge/service/aoj.py
readme.md

機能性を追加したのでマイナーバージョンを上げます。
せっかくなので `versionadded` みたいなのも書きました。

RELEASE: 6.1.0

---

onlinejudge/service/topcoder.py
tests/command_login.py

#292: implement TopcoderService.is_logged_in()

---

CHANGELOG.md
onlinejudge/__about__.py

実装した機能の実際の運用を Topcoder の MM109 でやってからバージョン上げる予定だったのですが、まったく結果発表してくれないので先にやってしまうことにしました。

RELEASE: 6.2.0

---

onlinejudge/_implementation/utils.py

Noneが入りうるからOptionalのはず。
ってかdefault値って型チェックされてないのかしら。

Fix type annotation

---

onlinejudge/_implementation/utils.py

以前の #314 では縦に長い文字列のみを省略していましたが、横に長い文字列も対象とするようにします。
-   `shutil.get_terminal_size` でターミナルの横幅を取得して利用しています。ドキュメントを読む限り、これは変な環境 (例えば Windows の cmd.exe とか) でも例外を吐かず動きます (https://docs.python.org/ja/3/library/shutil.html#shutil.get_terminal_size)
-   UI部分なのでテストは面倒で、省略しています
-   動作確認は例えば次のようなコマンドでできます: `oj t -c 'perl -e "print \"A\" x 3000000"'`。
例:
``` console
$ ./oj t -c 'perl -e "print \"A\" x 3000000"'
[*] 1 cases found
[*] sample-1
[x] time: 0.007890 sec
[-] WA
output:
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```

#313: print the summary of data, also in terms of chars, not only lines

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 6.2.1

---

onlinejudge/service/kattis.py

https になってないしそもそも繋がらなかったので修正します。たぶん typo

NONE: fix a typo of a URL of Kattis

---

onlinejudge/service/toph.py

close #430 
これは入れないと他の CI が全部落ちるので @fukatani のレビューを待たずマージします

#430: follow the change of the HTML structure on Toph

---

CHANGELOG.md
onlinejudge/__about__.py

バージョンを上げます。
@fukatani コードはないですが確認とマージお願いします

RELEASE: 6.3.0

---

onlinejudge/service/atcoder.py

NONE: add an argument `pages` to AtCoderContest.iterate_submissions_where()

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

CE なケースに対する提出の詳細を取得しようとすると落ちます。修正してテストも追加します。

NONE: fix a bug of AtCoderSubmission() for submissions whose status is CE

---

CHANGELOG.md
onlinejudge/__about__.py

バージョンを上げます。
たくさんになってしまったので Change Log は多くを省略しました。
@fukatani よさそうだったらマージボタン押してください。 (たくさんレビューありがとうございました)

RELEASE: 6.4.0

---

onlinejudge/_implementation/format_utils.py
onlinejudge/_implementation/main.py
onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py
tests/command_download.py
tests/command_download_atcoder.py
tests/command_submit.py

ここで全部キャッチした方が他のコマンドにも対応できますね。。

#365: catch error

---

readme.md

close #467 
GitHub 上を検索して見つかったものの一覧です。
もうすこしあった気がするけどそんなになかった。

#467: list projects depending on online-judge-tools

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

close #468 
すぐに落ちて面倒なので並列数を減らします

#468: disable the test of -j on AppVeyor

---

onlinejudge/_implementation/command/submit.py
tests/command_submit.py

#477 の問題に関するものです。
この折衷案なら互換性の意味でも設計の正しさの意味でもほぼノーコストなので、とりあえずやっておきます。
他のソフトウェアを見てもたいていこの挙動 (つまり引数の設定を許す) のはずです。Windows の場合は分からないのでとりあえずそのままにしておきました

#477: allow to call browser by commands at submit subcommand

---

CONTRIBUTING.md
readme.md

AppVeyor のまわりが上手くいったようなのでドキュメントの更新をします

#459: update document for GitHub releases and Windows binaries

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

#487 : Can't get a name of a contest without penalty

---

.travis.yml
CONTRIBUTING.md
onlinejudge/_implementation/command/generate_output.py
onlinejudge/_implementation/command/split_input.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/command/test_reactive.py
onlinejudge/dispatch.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/hackerrank.py
onlinejudge/service/toph.py
setup.cfg
setup.py
tests/command_download_anarchygolf.py
tests/command_download_aoj.py
tests/command_download_codeforces.py
tests/command_download_csacademy.py
tests/command_download_kattis.py
tests/command_download_poj.py
tests/command_download_toph.py
tests/command_generate_output.py

lint を導入します。とりあえず unused import の検出だけ有効にします。

NONE: use pylint to check unused import

---

CHANGELOG.md
readme.md

NONE: Add contributor name.

---

CHANGELOG.md

#496 で修正されたものですが、よく見たらちょっと違ってました。

NONE: fix a name of contributor in CHANGELOG.md

---

CONTRIBUTING.md

#496 の問題に関して、やっぱり書いておいた方がいいなと思ったので書いておきます。

NONE: update CONTRIBUTING.md

---

onlinejudge/service/hackerrank.py

#484 で説明した HackerRank のあたりの変数名について、コメントを足します。

NONE: add comment for the name of contest_slug of HackerRank

---

onlinejudge/service/atcoder.py

AtCoder の問題のサンプル取得の際に、問題名とかもすべてまとめて解析してたのをやめます。巻き込まれて落ちることが少なくなるはず。
(プルリクの宛先は `develop` です)

NONE: increase reliability of sample downloading from AtCoder

---

tests/service_atcoder.py

https://github.com/kmyk/online-judge-tools/pull/511 で突然 CI が落ちたやつを直します

NONE: fix a new error at tests/service_atcoder.py

---

docs/index.rst
docs/introduction.ja.rst

紹介文章を書きました。
https://kimiyuki.net/blog/2017/01/19/pr-online-judge-tools/ が完全に腐ってるので置き換えをします。
プレビューは https://github.com/kmyk/online-judge-tools/blob/a25b1bcce4e058e67012983d88af1f00025a01b7/docs/introduction.ja.rst にあります。最終的に公開されることになる URL は https://online-judge-tools.readthedocs.io/en/master/introduction.ja.html です。

NONE: add docs/introduction.ja.rst

---

tests/command_download_yukicoder.py
tests/command_submit.py
tests/service_yukicoder.py

NONE: fix problems of CI

---

CHANGELOG.md
onlinejudge/__about__.py

Windows まわりがいい感じになったのでここらでバージョンを上げたい
(#523 が入ったら rebase します)

RELEASE: 7.1.0

---

.appveyor.yml
.travis.yml
CONTRIBUTING.md
setup.cfg

テストの標準出力のログが多すぎてエラー箇所を探すのが大変なので、pytestがどんなもんか見てみます。

None: use pytest

---

CHANGELOG.md
onlinejudge/__about__.py

バージョンを更新します。Library Checker 対応だけだけど、早めに公開しておきたいので

RELEASE: 7.2.0

---

.travis.yml
onlinejudge/_implementation/utils.py

None: Use cover all.

---

docs/introduction.ja.rst

None: Update introduction.

---

CONTRIBUTING.md

About coverage

---

tests/command_test.py

#538: Add float compare test.

---

readme.md

gitter で話していたやつです。
私の英語力だと何をどう書いても悪意あるように読まれてしまう気がするので、丸ごと削る感じにしました。

NONE: remove unnecessary words from readme.md

---

onlinejudge/_implementation/command/test.py
tests/command_test.py
tests/utils.py

カバレッジは上がりますが、
そもそもこの機能使うのか？サポートを継続すべきなのか？テストではlineとallの違いがテストされてないけどいいのか？という疑問はあります。
いずれにしても複数行期待値のテストは必要です。

#438: Add test for line mode.

---

tests/command_version.py

このPRはレポートを確認してテストが実行されたことを確認します。

None: fix test name.

---

CHANGELOG.md
onlinejudge/__about__.py
readme.md

Merge after #561 .
I want fixed `Codeforces.list_problems`.

Release 7.2.2

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/command/submit.py

Maybe thanks to mypy update, part of `type: ignore` is unnecessary.

remove unnecesarry type : ignorance

---

readme.md

- バッチが多くなり過ぎてたので減らします。それぞれで見ると「ないよりはある方がよい」ようなものであったとしても、無闇にたくさん並べると「ごちゃごちゃしてよく分からない」「すべてが目立たない」ものになるためです
- 文中にもいくつかバッチを貼ります。目立たせる意味の他に、バッチをクリックできることを自然に知ってほしいという意図もあります

update readme about the badges

---

tests/type.py

This part is not covered and I used this feature in my IDE. Therefore I want to test here.

Add unittests for __eq__

---

CHANGELOG.md
onlinejudge/__about__.py

8.0.0か迷いましたが、8.0.0にふさわしい機能が思い浮かんだ気もするので、とっておきます。

RELEASE 7.3.0

---

onlinejudge/service/anarchygolf.py
tests/command_download_anarchygolf.py
tests/service_anarchygolf.py

Related to: #573 #155
In this PR,
- Create `tests/anarchygolf.py` and add some tests.
- <s>Apply `utils.parse_content` to `onlinejudge/service/anarchygolf.py`.</s>
- <s>Apply `utils.textfile` to `onlinejudge/service/anarchygolf.py` when `Sample Input` is `*NOTHING*`. [Example](http://golf.shinh.org/p.rb?hello+golfers)</s>
- <s>Fix `test_call_download_anarchygolf_hello_world` related to above application.</s>
- Fix `_parse_sample_tag` in `onlinejudge/service/anarchygolf.py`.
- Remove  `utils.textfile`.
- Add comments.
- Fix `tests/command_download_anarchygolf.py` to adjust above change.

Improve anarchygolf

---

CHANGELOG.md
readme.md

close https://github.com/kmyk/online-judge-tools/issues/601
@kawacchu is now a maintainer!
This pull request update some documents for this.
---
@kawacchu please check this pull request and merge if there is no problem.

@kawacchu joined as a maintainer 🎉

---

onlinejudge/service/aoj.py

@beet-aizu に教えてもらったやつを記録のためコメントとして残しておく

add a comment about the limitation of API of AOJ

---

tests/command_download_codeforces.py

[https://codeforces.com/gym/101021/problem/A](https://codeforces.com/gym/101021/problem/A)が無効なURLになっているようなので、別の問題に差し替えました。

Fix tests/command_download_codeforces.py

---

CHANGELOG.md
onlinejudge/__about__.py

せっかく @btk15049 さんが頑張ってくれた新機能なので早めにリリースしたい。
version 番号については、特に後方互換性の大きな破壊的はないはずなのでとりあえず minor version を上げています。

RELEASE 7.4.0

---

onlinejudge/_implementation/utils.py
onlinejudge/service/hackerrank.py

close #629 
HackerRank の更新に対応します。CI が落ちてるのが直ります。
ところで Kattis は関係なかったぽいです。

fix for HackerRank

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

Close: #602 
I tested locally.
I need your help if we make test function :bird:

Fix UnicodeDecodeError problem

---

CHANGELOG.md
onlinejudge/__about__.py

#613 が入ったらバージョンを上げたいです。
AOJ のサンプルに関するものなどはどちらかと言えば patch version より minor version を上げたい気がするので、7.4.1 でなく 7.5.0 にしてあります。

RELEASE: 7.5.0

---

onlinejudge/service/toph.py

Apply parse_content to toph

---

tests/command_test.py

#640
とりあえずテストだけ足します
以前直したはずなのに再発してたので

add a test about zombie processes

---

CHANGELOG.md
onlinejudge/__about__.py

バージョン更新です。API が増えたので minor バージョンを上げます。
(内部の関数を使いたいという話だったのに公開まで遅くなったのよくなかった気がする。@yosupo06 すまん)

RELEASE: 7.6.0

---

onlinejudge/utils.py

公開は尚早な気がするので、消します。
`user_data_dir`と`user_cache_dir`もこのまま公開すべきものなのか、迷っています。

remove user_config_dir

---

onlinejudge/_implementation/main.py
onlinejudge/type.py

以下をすべて統一します:
- 例外の引数でメッセージを書けば表示される
- `--verbose` を付ければ stack trace が表示される
- exit code は 1

refactoring about messages of exceptions

---

onlinejudge/service/__init__.py
onlinejudge/service/spoj.py
readme.md
tests/service_spoj.py

#651 
大分性能が低い。
できるやつ
https://www.spoj.com/problems/ACARGO/
無理なやつ
https://www.spoj.com/problems/MKLABELS/

Support Sphere online judge.

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/main.py
onlinejudge/service/yukicoder.py

https://github.com/kmyk/online-judge-tools/issues/672#issue-561671705 を実装しました

support yukicoder token

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 8.0.0

---

CHANGELOG.md
onlinejudge/__about__.py

はやめに更新しておきます。明らかな破壊的変更があるので major version を上げます。

RELEASE: 9.0.0

---

readme.md

古くなってたので更新します。
https://github.com/jmerle/competitive-companion と https://github.com/kmyk/online-judge-verify-helper の紹介を漏らしてるのはよくない。

Update Related Tools section of readme.md

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

Fix side-by-side-display line number

---

onlinejudge/_implementation/utils.py
tests/command_test.py

fix #640 
Mac での動作が不安なので環境がある人がいれば試してほしい @fukatani @kawacchu

Kill zombies caused by time command

---

onlinejudge/_implementation/command/download.py

fix #695 
before:
``` console
$ oj d https://atcoder.jp/contests/dwacon6th-final-open/tasks/dwacon6th_final_d
[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/dwacon6th-final-open/tasks/dwacon6th_final_d'): https://atcoder.jp/contests/dwacon6th-final-open/tasks/dwacon6th_final_d
[x] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
[x] GET: https://atcoder.jp/contests/dwacon6th-final-open/tasks/dwacon6th_final_d
[x] 200 OK
[x] save cookie to: /home/user/.local/share/online-judge-tools/cookie.jar
[x] append history to: /home/user/.cache/online-judge-tools/download-history.jsonl
[*] sample 0
[x] input: sample-1
8
1
2
1
4
1
6
4
2
1
2
1
2
3
4
2
[ERROR] Failed to download since file already exists: test/sample-1.in
```
after:
``` console
$ oj d …
```

Make the download subcommand atomic

---

CHANGELOG.md
onlinejudge/__about__.py

急ぎなので先に #718 だけ release したい。バグ修正なので patch version を上げます

RELEASE: 9.1.1

---

readme.md

ref #711 
メンテナ含め3回以上聞かれたので足しておく

Add the question about delays of submission to FAQ

---

onlinejudge/_implementation/main.py
onlinejudge/service/__init__.py
onlinejudge/service/google.py
readme.md
tests/service_google.py

Google Code Jam

---

CHANGELOG.md
onlinejudge/__about__.py
onlinejudge/service/google.py

次の GCJ R1A に間に合わせるための更新です。
@fukatani 更新作業や告知は私がやります (「土曜までに更新しておけよ」を強調しておきたいので)。

RELEASE: 9.2.0

---

CHANGELOG.md
onlinejudge/__about__.py

update the version for the errors fixed by #728

RELEASE: 9.2.1

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 9.2.2

---

onlinejudge_command/main.py
onlinejudge_command/update_checking.py
onlinejudge_command/utils.py

Now there is two main dependencies, so we need to update the update checking.

Update the update checker

---

CHANGELOG.md

コードは変化したし API も所属が分離されたので major version を上げないとだめ。でも機能的には何も増えてない (つまりエンドユーザにとっては新規にバグが混入した危険性だけがある)

RELEASE: 10.0.0

---

onlinejudge_command/download_history.py
onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/update_checking.py
onlinejudge_command/utils.py
setup.py
tests/command_download_atcoder.py
tests/command_download_invalid.py
tests/command_download_yukicoder.py
tests/command_login.py
tests/command_submit.py
tests/implementation_language_guessing.py

close #755
see https://github.com/online-judge-tools/api-client/pull/26

Add a workaround for the confliction

---

onlinejudge_command/utils.py
tests/command_test.py

Kill processes when Ctrl-C is pressed

---

onlinejudge_command/update_checking.py

Fix the message to encourage upgrade packages

---

README.md
onlinejudge_command/main.py

はじめまして。
CONTRIBUTING.mdが最近削除されたようなのですが、一部のリンクがまだ
残っているようなので削除しました。
なお、コマンドのINFOについては、CONTRIBUTINGに誘導するのではなく、
レポジトリのホームに誘導するようにしました。

Remove link related contributing.md

---

onlinejudge_command/utils.py

コードは長くなってつらいが、テストしやすくメンテしやすい感じに

Refactor utils.make_pretty_large_file_content and fix a bug

---

onlinejudge_command/subcommand/login.py

Add a hint message to install WebDriver

---

onlinejudge_command/subcommand/generate_input.py

Fix logging of generate-input subcommand

---

CHANGELOG.md
onlinejudge_command/__about__.py

RELEASE: 10.1.3

---

onlinejudge_command/output_comparators.py
tests/command_test.py
tests/output_comparators.py

Write unit tests about output comparators

---

onlinejudge_command/output_comparators.py
onlinejudge_command/pretty_printers.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/generate_input.py
onlinejudge_command/subcommand/generate_output.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/subcommand/test.py
onlinejudge_command/utils.py
tests/pretty_printers.py

Add tests for the internal pretty printer

---

.github/workflows/format.yml
.github/workflows/test.yml
onlinejudge_command/download_history.py
onlinejudge_command/format_utils.py
onlinejudge_command/main.py
onlinejudge_command/output_comparators.py
onlinejudge_command/pretty_printers.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/generate_input.py
onlinejudge_command/subcommand/generate_output.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/subcommand/test.py
onlinejudge_command/update_checking.py
onlinejudge_command/utils.py
setup.cfg
setup.py
tests/command_download.py
tests/command_download_invalid.py
tests/command_login.py
tests/command_submit.py
tests/implementation_language_guessing.py

close https://github.com/online-judge-tools/oj/issues/809

Finish Python 3.5 support

---

onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/test.py
tests/command_test.py

#824 対応
StreamHandlerを標準エラー出力から標準出力に変更しました

Change StreamHandler to stdout from stderr

---

onlinejudge_command/download_history.py
onlinejudge_command/log_formatter.py
onlinejudge_command/main.py
onlinejudge_command/pretty_printers.py
onlinejudge_command/subcommand/generate_input.py
onlinejudge_command/subcommand/generate_output.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/test.py
onlinejudge_command/utils.py
setup.cfg
tests/command_generate_input.py
tests/command_generate_output.py
tests/command_login.py
tests/command_test.py
tests/utils.py

ミスをレビューで指摘されるとなんとなくしんどいけど、type checker や linter に指摘されるとなにも思わず直せるみたいなとこないですか？ みんなが楽になるので強めにしておきましょう

Configure pylint to enable more warnings

---

onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/test.py
tests/command_test.py

Add log file option

---

onlinejudge_command/main.py

#839 のついで
元のコードが悪いだけのやつなので自分で修正しておく

Use utils.HINT for [HINT] messages

---

CHANGELOG.md
onlinejudge_command/__about__.py

RELEASE: 11.1.1

---

README.md
docs/INSTALL.md
docs/getting-started.ja.md
docs/getting-started.md

continued from https://github.com/online-judge-tools/oj/pull/842

Update the contents of documents

---

README.md
docs/INSTALL.ja.md
docs/INSTALL.md
docs/getting-started.ja.md
docs/getting-started.md

continued from https://github.com/online-judge-tools/oj/pull/844

Translate docs/INSTALL.md to Japanese

---

docs/getting-started.ja.md
docs/getting-started.md

continued from https://github.com/online-judge-tools/oj/pull/845

Translate the "Missing features" section to English in docs/getting-started.md

---

CHANGELOG.md
onlinejudge_command/__about__.py

RELEASE: 11.1.3

---

docs/getting-started.ja.md
docs/getting-started.md
onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/generate_input.py
onlinejudge_command/subcommand/generate_output.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/subcommand/test.py
onlinejudge_command/subcommand/test_reactive.py
setup.cfg
tests/command_download.py
tests/command_submit.py
tests/command_test_reactive.py
tests/utils.py

refactoring about subcommands

---

README.md

Add a link to @danpe919's post from README.md

---

CHANGELOG.md
onlinejudge_command/__about__.py

RELEASE: 11.2.0

---

onlinejudge_command/subcommand/download.py
setup.py

related https://github.com/online-judge-tools/api-client/issues/60
depends on https://github.com/online-judge-tools/api-client/pull/139
cc @qryxip

Add --dropbox-token option for AtCoder's system cases

---

onlinejudge_command/subcommand/submit.py

この wait は必要だと思うんですけど、それはそれとして不満もあるぽいので見えないようにしておく

Don't show "sleep(3.0)"

---

onlinejudge_command/utils.py

Fix the issue that terminal is cleared after submission

---

onlinejudge_command/utils.py

Fix the issue of terminal logs again

---

onlinejudge_command/main.py
onlinejudge_command/subcommand/test_reactive.py

Add `test-interactive` and `t/i` as aliases of `test-reactive`

---

CHANGELOG.md
onlinejudge_command/__about__.py

RELEASE: 11.4.0

---

onlinejudge_command/subcommand/generate_input.py
tests/command_generate_input.py

Allow --hack-actual without --hack-expected

---

onlinejudge_command/pretty_printers.py
tests/pretty_printers.py

Fix a bug of --display-mode=diff-all

---

.github/workflows/format.yml
.github/workflows/test.yml
onlinejudge_command/download_history.py
onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/generate_input.py
onlinejudge_command/subcommand/generate_output.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/subcommand/test.py
onlinejudge_command/subcommand/test_reactive.py
onlinejudge_command/utils.py
setup.cfg
setup.py
tests/implementation_language_guessing.py

Python 3.6 and 3.7 will be no longer supported.

feat!: bump minimum Python version to 3.8
