online-judge-tools/oj

onlinejudge/implementation/command/test.py

generate-output: ignore the output when runtime error caused

---

onlinejudge/codeforces.py

codeforcesへログインできなかったので修正しました。
現在のログインページではusernameを格納するパラメータ名が変更されているようです。

fix login feature for codeforces

---

onlinejudge/implementation/command/submit.py

概要
==
submit時、IDの代わりに文字列で入力したいです(毎回テーブル調べるのが面倒なため)
入力例
==
正常時
```
oj s -l rust ...
[*] choosed language: ['Rust (1.15.1)']
```
Rust (1.15.1)を選択したものとして、処理を続行します。
異常時１
```
oj s -l python ...
[ERROR] Matched languages were not narrowed down to one.
[*] You have to choose:
Python2 (2.7.6)
Python3 (3.4.3)
```
Python2 (2.7.6)かPython3 (3.4.3)か絞れないので、どっちか選んでねとメッセージ出して処理をストップします。
異常時2
```
-l aaaa
[ERROR] language is unknown
[*] supported languages are:
3001 (Bash (GNU bash v4.3.11))
3002 (C (GCC 5.4.1))
...
```
そんなものはないぞ、ということで従来通りのエラーメッセージを出します。
どうでしょうか？

feature: select submit language by name

---

onlinejudge/aoj.py

AOJからのサンプルケースの取得が動作していなかったのを修正しました。
AOJのhtmlパース時のパーサーの指定を`lxml`から`html.parser`に変更しました。
- macOS 10.13.6
- Python 3.7.0
```
$ python3 -V
Python 3.7.0
$ pip3 -V
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ pip3 show online-judge-tools lxml beautifulsoup4
Name: online-judge-tools
Version: 0.1.39
Summary: Tools for online-judge services
Home-page: https://github.com/kmyk/online-judge-tools
Author: Kimiyuki Onaka
Author-email: kimiyuki95@gmail.com
License: MIT License
Location: /usr/local/lib/python3.7/site-packages
Requires: requests, sympy, lxml, colorama, beautifulsoup4
Required-by:
---
Name: lxml
Version: 4.2.5
Summary: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Home-page: http://lxml.de/
Author: lxml dev team …
```

fix download sample cases from judge.u-aizu.ac.jp

---

.travis.yml
onlinejudge/aoj.py
onlinejudge/atcoder.py
onlinejudge/codeforces.py
onlinejudge/dispatch.py
onlinejudge/implementation/command/generate_scanner.py
onlinejudge/implementation/command/submit.py
onlinejudge/implementation/command/test.py
onlinejudge/implementation/command/utils.py
onlinejudge/implementation/utils.py
onlinejudge/topcoder.py
onlinejudge/yukicoder.py
readme.md
setup.py

とりあえずテストは通しました。手元ではatcoderだけ軽く試しています。
jsonはdecode('UTF-8')すればいけたのと、Python3.5のargparseは--systemが最後のコマンドライン引数だとエラーになりましたので修正しました。
ついでにbranch名に限らずテストされるようにしました。
Python3.5対応するかどうかはお任せします。（個人的には嬉しいですが、3.6しかやらんぞというのもまた決断）
型アノテーションの書き方はPython3.6で書かれている書き方のほうがわかりやすいですね。

support python3.5

---

.travis.yml
onlinejudge/implementation/command/generate_output.py
onlinejudge/implementation/command/test.py
onlinejudge/implementation/command/utils.py
onlinejudge/service/atcoder.py
tests/command_test.py

/home/ryo/work/github/rust-debug/src/
というディレクトリにおいて
oj test -c ./a.out -d ./testを行うと、
```
File "/home/ryo/.virtualenvs/default/bin/oj", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "/home/ryo/work/github/online-judge-tools/oj", line 6, in <module>
onlinejudge.implementation.main.main(args=sys.argv[1:])
File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/main.py", line 345, in main
run_program(namespace, parser=parser)
File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/main.py", line 320, in run_program
test(args)
File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/command/test.py", line 41, in test
tests = …
```

[WIP] oj testでディレクトリ指定できないバグ修正

---

onlinejudge/implementation/format_utils.py

ローカルのフォーマッタのせいでdiffが荒れてしまったのは
申し訳ないです

#256 regexpやglobにエスケープ処理を追加

---

onlinejudge/implementation/command/login.py

メッセージを足しただけ
mergeは #286 が入ってから

#276: add a message to tell the option that login with session tokens

---

.travis.yml

よく考えたらこの部分のテストがない (`python3 setup.py test` とかだと `./oj` を参照するので)

#290: add tests to check the installer

---

LOGIN_WITH_COOKIES.md

-   手順3はアクセスがあればよくてloginを試す必要はなさそうなので修正
-   いくつかの文字列をquoteしたり色を付けたりする
-   (実際の出力としては嘘だけど、何も考えずコピペする人のために) `/home/ryo` を `~` で置き換え

#276: fix some parts of LOGIN_WITH_COOKIES.md

---

docs/onlinejudge.service.rst
onlinejudge/implementation/command/download.py
onlinejudge/implementation/main.py
onlinejudge/implementation/utils.py
onlinejudge/service/__init__.py
onlinejudge/service/hackerrank.py
readme.md
tests/command_download.py
tests/command_download_hackerrank.py
tests/command_login.py
tests/command_submit.py

close #208 
close #151
復活させました

#208 support HackerRank again

---

CONTRIBUTING.md

Improve contrib guide

---

onlinejudge/implementation/utils.py
onlinejudge/service/atcoder.py
tests/service_atcoder.py

#318 #317 add features to list contests and problems of AtCoder

---

onlinejudge/implementation/command/download.py
onlinejudge/implementation/command/generate_output.py
onlinejudge/implementation/command/submit.py
onlinejudge/implementation/command/test.py
onlinejudge/implementation/utils.py

close #314 
出力が次のようになります。
「ちゃんと取得ミスがないか確認しろよ」という意図での出力なのに、すべて出力すると確認にならないどころか他の警告まで隠してしまう場合がありました。これを直します。
「省略なし」を指定するオプションも必要になってしまってつらいですが、これはしかたないので諦めて足す予定です。適切なオプション名を考えてないので別のプルリクになります。
```
test_call_submit_beta_3_b (tests.command_submit.SubmitCodeforcesTest) ... [x] read history from: /home/user/.cache/online-judge-tools/download-history.jsonl
[x] found urls in history:
[x] problem recognized: <onlinejudge.service.codeforces.CodeforcesProblem object at 0x7f2c814bda20>: https://codeforces.com/contest/3/problem/B
[*] code (1477 byte):
#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define ALL(x) begin(x), end(x)
using namespace std;
int main() {
// input
int n, v; cin >> n >> v;
vector<pair<int, int> > one;
vector<tuple<int, int, int> > two;
... (40 …
```

#314 + snip too large outputs for all subcommands

---

onlinejudge/_implementation/command/get_standings.py
onlinejudge/service/topcoder.py
onlinejudge/type.py

`problem.get_standings()` is used only for Topcoder Marathon Match. This should be removed from the abstract class `Problem`

#318: remove problem.get_standings()

---

onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py
tests/service_atcoder.py

先にpropertyだけ置いておいた部分の中身の実装です。問題名とかがURLから直で取れるようになります

#318: add a function to get information of problems

---

onlinejudge/service/topcoder.py
onlinejudge/service/yukicoder.py

`Deprecated since version 6.0.0: This method may be deleted in future.` みたいに書かれます。
これを書いておけば互換性を切る変更ができます。仕様が固まってないメソッドなので必要な措置です。

#318: write cautions for experimental methods

---

.travis.yml
onlinejudge/service/yukicoder.py
tests/command_download_yukicoder.py
tests/service_atcoder.py
tests/service_codeforces.py
tests/service_yukicoder.py

pre.previous_siblingとtestの修正をまとめて一つにしています。
もし何か間違っていたら再度修正します。

#355: fix pre.previous_sibling become None Bug at yukicoder

---

onlinejudge/service/atcoder.py

close #166 
旧AtCoderに依存していた部分を新AtCoderで置き換えます。
@fukatani コードの他に、AtCoderから送られてくるエラーメッセージの処理が正しく動いてそうか簡単にでよいので確認してほしいです。

#166 use the new version of AtCoder

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

#318: add the feature to get information of contests from AtCoder

---

onlinejudge/service/atcoder.py

`AtCoderProblem.submit_code` が `AtCoderSubmission` を返すようにします
https://online-judge-tools.readthedocs.io/en/master/onlinejudge.service.atcoder.html#onlinejudge.service.atcoder.AtCoderProblem.submit_code

#360: let AtCoderProblem.submit_code return AtCoderSubmission

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/command/generate_scanner.py
onlinejudge/_implementation/command/login.py
onlinejudge/_implementation/command/submit.py
onlinejudge/_implementation/utils.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/hackerrank.py
onlinejudge/service/kattis.py
onlinejudge/service/poj.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py

例えば次のような流れのコードが (1行目でログインが成功したとしても) 2行目で `NotLoggedInError` みたいになるのはかなり不親切に思えるので、global変数を用いてこれを解決します。
``` python
problem.get_service().login()
problem.submit_code(code)
```

#375: prepare the global default session

---

onlinejudge/service/atcoder.py

以下の3点です
-   `_with` より `_where` の方が適切 (AtCoder鯖上で走っているだろうSQLを連想させるため)
-   ドキュメント足りないのを追加
-   `AtCoderProblem` にも `_where` を生やす

#375: update around AtCoderContest.iterate_submissions

---

setup.cfg

現状は readme がそのまま表示されてて汚ない (https://pypi.org/project/online-judge-tools/0.1.55/) のですが、これを解決します。
https://packaging.python.org/guides/making-a-pypi-friendly-readme/ によると、これを指定するといい感じにしてくれるらしいです。

NONE: set long_description_content_type = text/markdown at setup.cfg

---

onlinejudge/_implementation/command/login.py
onlinejudge/_implementation/command/submit.py
onlinejudge/_implementation/utils.py

close #393 
上のようないかにもバグの温床な書き方をしてたのが原因なので、ちゃんと下のように直しました
https://github.com/kmyk/online-judge-tools/blob/5ae56183b6b92a1cba5c0b39dcb7e21a03c89708/onlinejudge/_implementation/command/submit.py#L131
https://github.com/kmyk/online-judge-tools/blob/ff7bb1b419f5dc90cadc0b359842743d6b51bd39/onlinejudge/_implementation/command/submit.py#L131

#393: fix the degression of the `submit` subcommand for Topcoder with `--full-submission`

---

onlinejudge/service/atcoder.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py
tests/service_atcoder.py
tests/service_yukicoder.py

close #380
なんだか複数になってしまったが、やったのは以下です。
-   #380 で議論した形で仕様を固定
-   #380 のバグを修正
-   その他のバグもついでに修正

#380: fix AtCoderProblem.get_input_format()

---

onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py
onlinejudge/service/topcoder.py
onlinejudge/type.py
tests/service_atcoder.py
tests/type.py

close #402
- `abc.ABC` や `__repr__` は機能というより設計方針を明確にするためのドキュメントのつもりです
- 差分は小さくないですが、どれもすべて元々あったコードを移動したものです
- コードは汚ないですが、インターフェースの綺麗さを優先した結果です (これは Python 3.5 の対応を切れば解決します https://docs.python.org/ja/3.6/library/typing.html#typing.NamedTuple)
- テストは何も削っていません
- 後方互換性はすべて保ったはずです
@fukatani レビューお願いします :pray:

#402: add the class AtCoderProblemContent

---

onlinejudge/service/topcoder.py
tests/service_topcoder.py

close #403 
かなりそのままな形で実装しました。
`cr` `rd` のような妙な名前は Topcoder 側のしている省略に合わせています。
型名がすごく長いですが、短くするよりましだと思ったのでこうなってます。

#403: add a feature to download MatchOverview of Topcoder Marathon Match

---

onlinejudge/service/topcoder.py
tests/service_topcoder.py

#406 のついでです。
- 型を変えたので互換性は壊れました
- method名を変えたのはついでです。変えても問題ないタイミングで「毎回通信が発生しそうな」名前にしたかった
- テストがないのは仕様です。コンテスト開催中しか動かないのでテストには mock を書くしかなくて面倒です。加えて、ユーザの性質 (MMに参加していて、順位表の解析という発想を持っていて、Pythonライブラリを利用できる) から、彼らからのバグ報告が来ることに頼ってしまってよいはずです

Update the feature to use module=ViewStandings of Topcoder Marathon Match

---

setup.cfg

close #409 
不要な依存関係は (ユーザにとって) 邪魔なだけなので消します

#409: remove sympy from setup.cfg

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

close #412
運よく byte を単位として持っていたので、型は変えずにそのまま修正できました。

#412: allow non-integers for memory limits in AtCoder

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

close #411 
落ちないようにだけして取得は放棄しています。主には以下の2点が理由です。
1.  他にも `$100$` とか `<var>100</var>` とか色々でてきそう
1.  そもそも点数情報は順位表から取るべきだった

#411: add a workaround for the scores surrounded by \( \) in AtCoder

---

onlinejudge/_implementation/command/test.py

It happens if the user program causes a runtime error on a test case
without *.out file.
---
バグ修正です。再現条件はコミットメッセージの通りです。
期待される挙動 (修正後):
``` console
$ oj t -i
[*] foo-1
xxxxx
[x] time: 0.157908 sec
[-] RE: return code 134
input:
yyy
output:
zzz
```
変な挙動 (修正前):
``` console
$ oj t -i
[*] foo-1
xxxxx
[x] time: 0.157908 sec
[-] RE: return code 134
input:
yyy
zzz
```

NONE: fix a lack of a header, in test subcommand with --input option

---

onlinejudge/service/aoj.py
tests/command_download_aoj.py

close #429 
AOJ のシステムケースを取得する際に `..... (terminated because of the limitation)` と言われて途中で打ち切られる問題がありましたが、これを解決します。

#429: avoid the limitation of the new API of AOJ

---

onlinejudge/_implementation/command/generate_output.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/main.py
onlinejudge/_implementation/utils.py

close #427 
実行時間制限を付けるオプション `--tle` を、サブコマンド `test` だけでなくサブコマンド `generate-output` でも使えるようにします。
これに伴なって、 `--tle` による実行打ち切り後もプロセスが死なず動き続ける問題の修正もします。
@fukatani レビュー時の注意として:
-   微妙に性質の違うコミットふたつなのでプルリクを分けるべきかもしれないが、衝突するのでまとめました
-   テストがないけど書くの面倒なので許して
-   プロセスの処理はプロセスグループを使ってやるしか手がなかったです。Windows上ではたぶん動かないので無効化しています

enhancement about --tle option

---

onlinejudge/service/atcoder.py

For urls like "https://atcoder.jp/contests/abc128/tasks/abc128_a",
AtCoderContest.from_url() returns None.
This commit will fix it.

Bug fix of AtCoderContest.from_url()

---

onlinejudge/_implementation/format_utils.py
onlinejudge/_implementation/testcase_zipper.py
setup.cfg

#362 を思い出したのでやります。
@kotamanegi たぶん動くのだけど WIndows 環境下でのテストがしんどいのでよかったら手伝ってほしい

#362: use "entry_points" instead of "scripts" in setup.cfg

---

onlinejudge/_implementation/format_utils.py
tests/command_test.py

close #437
https://github.com/kmyk/online-judge-tools/blob/49b2af11f6c4120dc79b7281e1837d82b9883296/onlinejudge/_implementation/format_utils.py#L78-L80
この `path.stem` が原因でした。これだと `/path/to/sample.in` のようなものに対し `sample` が返ってきてしまうので間違いで、 `path.name` が正解です。
テストも足しました。

#437: fix a bug around --ignore-backup of test subcommand

---

onlinejudge/_implementation/command/generate_output.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/main.py
tests/command_generate_output.py
tests/command_test.py

close #428
テストを並列で実行できるようにします。
コンテスト中に「入力をランダムに生成して愚直解との不一致が現われるまで試し続ける」のような処理をする場合の利用を想定しています。
レビュー時の注意として:
-   元々のコードがそろそろ限界な感じだったのでリファクタリングのコミットもしています。
-   排他制御に気を付けてください。適当にやると異なるケースの出力が混ざって混乱するので、その回避のために `threading.Lock` を用いています。
-   標準エラー出力については特別な処理をせず、そのままターミナルに流す仕様です。
@fukatani :pray:

#428: make test possible to run in parallel

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

close #444
ペナルティの表記に `minute` の形があることを見落としていていました。これを修正します。

#444: fix a bug of AtCoderContest.get_penalty()

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

close #446 
`0.5 sec` でなくて `500 msec` が来るせいで落ちるバグを修正します

#446: fix a bug with time limits which are less than 1 sec

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

#446 と同根の問題です。メモリ制限が 0 MB のときに、 `0 MB` でなく `0 KB` が来るので落ちる問題を解決します。

NONE: fix a bug with problems whose memory limit is 0 KB of AtCoder

---

onlinejudge/service/atcoder.py
tests/service_atcoder.py

AtCoder の問題の点数は整数とは限らないのですが、これによる例外が飛んでいました。型の変更と修正をします。

NONE: scores of problems of AtCoder can be floating point numbers

---

onlinejudge/_implementation/command/generate_output.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/main.py
onlinejudge/_implementation/utils.py
tests/command_test.py

close #312 
うっかり MLE しないようにメモリ使用量を監視する機能を足します。
具体的な仕様は次のようになります。
-   それぞれのテストケースで:
-   メモリ使用量が 500MB より大きいなら目立たせて出力して警告
-   メモリ使用量が 100MB より大きいならとりあえず出力
-   メモリ使用量がそれ以下なら邪魔なので非表示 (オプションを指定で出力)
-   最後には常にメモリ使用量を出力 (同じ条件で必要なら目立たせて警告)
---
実装には GNU `time`  (`/usr/bin/time` とかにあるやつであって、shell builtin の `time` コマンドとは異なる) を利用しています。
メモリ使用量を監視するのは一般に面倒で (ある時刻の使用量でなくて実行開始から終了まででの全時刻の最大を取らないとだめ、監視対象のプロセスをきちんと指定しないとだめ、別プロセスのメモリ使用量を好き勝手に取得するのはセキュリティの問題がある)、 他のよい方法は思い付きませんでした。
もちろん `time` が常に存在するとは限らないですし、存在しても互換性の問題がないとも限らないので、とりあえず使ってみて動くかどうかを判断する処理も含んでいます。
@fukatani これもレビューが簡単ではないものですが、よろしくお願いします :bow:

#312: add a feature to check MLE

---

CHANGELOG.md
onlinejudge/__about__.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/utils.py
tests/command_test.py

`time` コマンドの呼び出したプログラムのリターンコードが非0だった場合にエラーになることに気付きました。次に示すような `Command exited with ...` という行が紛れ込んできて落ちます。これを修正します。
``` console
$ \time -f %M -- perl -e 'die "hoge"'
hoge at -e line 1.
Command exited with non-zero status 255
4840
```
``` console
$ oj t
[*] 3 cases found
[*] sample-1
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/debug/vector:417:
Error: attempt to subscript container with out-of-bounds index 7, but 
container only holds 7 elements.
Objects involved in the operation:
sequence "this" @ 0x0x11adf88 {
type = std::__debug::vector<int, std::allocator<int> >;
}
File "/home/user/.local/bin/oj", line 10, in <module>
sys.exit(main())
File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", …
```

NONE: fix a bug of the memory checking

---

CONTRIBUTING.md

`pip install -e .`で開発中のonline-judge-toolsをインストールできるって説明を加えたほうがいいかなと思うのですが、どうでしょう？

NONE: Add how to install development version oj

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/main.py

before
```
$ oj download https://abc103.contest.atcoder.jp/tasks/abc103_
[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/abc103/tasks/abc103_'): https://abc103.contest.atcoder.jp/tasks/abc103_
[x] load cookie from: /home/ryo/.local/share/online-judge-tools/cookie.jar
[x] GET: https://atcoder.jp/contests/abc103/tasks/abc103_
[x] 404 Not Found
[!] AtCoder says: × Task not found.
[!] are you logged in?
File "/home/ryo/workspace/github/chainer-wind-env/bin/oj", line 11, in <module>
load_entry_point('online-judge-tools', 'console_scripts', 'oj')()
File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/_implementation/main.py", line 284, in main
run_program(namespace, parser=parser)
File …
```

#365: Catch HTTPError

---

onlinejudge/_implementation/main.py
onlinejudge/service/__init__.py
onlinejudge/service/facebook.py
readme.md
tests/service_facebook.py

Facebook Hacker Cup (https://www.facebook.com/hackercup/problem/2390352741015547/ とか) の問題からのサンプル取得を可能にします。
FHC は年に数回だけなので嬉しさはそう大きくないのだけれど、簡単にできるのでとりあえずやってみた感じです。

NONE: support downloading samples from Facebook Hacker Cup

---

CHANGELOG.md
docs/onlinejudge.service.facebook.rst
docs/onlinejudge.service.rst
onlinejudge/__about__.py
onlinejudge/service/facebook.py

> ですね、461と460は少し後になっちゃいそうなので、今のmasterでバージョンを上げるのが良いと思います！
(https://gitter.im/online-judge-tools/community?at=5d1dfc3a84cbda1764cc4a65) ということだったので、バージョンを上げます。
---
@fukatani レビューと、よさそうならマージをお願いします。
PyPI の更新もついでにお願いします。マージしたらそのマージ後の `master` に `v6.5.0` という git tag を貼って GitHub へ反映させてください。 https://github.com/kmyk/online-judge-tools/blob/master/CONTRIBUTING.md#deployment の (2.) です。
ついでに Twitter での告知も (もしよければ) やってみてください。

RELEASE: 6.5.0

---

onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/main.py
onlinejudge/_implementation/utils.py
tests/command_test.py

#312 でやり残していた `--mle` オプションの追加をします。
わざわざ指定するのは面倒なので、この `oj` を直接利用するユーザにはあまり嬉しさはないのですが、上部の高品質な wrapper 経由で叩くユーザにとっては嬉しいはずです。

#312: add --mle option for test subcommand

---

.appveyor.yml
tests/utils.py

close #459 
`oj.exe` に対するテストを書きました。
これでテストが成功していることは https://github.com/kmyk/online-judge-tools/tree/feature/test-oj-exe-fail の https://github.com/kmyk/online-judge-tools/commit/a237aaad6783ccdd564ac65e1a56102c43d329ab が落ちていることから確認してください。

#459: enable the unit test to run for specified oj.exe

---

CHANGELOG.md
onlinejudge/__about__.py

バージョンを上げます。
AppVeyor の deploy の設定の確認が目的です。
@fukatani マージしたら tag `v6.6.0` を打って GitHub に反映させてください。GitHub release や `oj.exe` のまわりが上手くいっていれば、Twitter での告知もお願いします。

RELEASE: 6.6.0

---

docs/index.rst
docs/run-ci-on-your-library.rst

競プロライブラリ上で CI を回したい人のためのドキュメントです。
私以外に誰も書きそうにないやつなので @beet-aizu の https://github.com/beet-aizu/library に投げたついでに書いておきました。
-   英語で書くべきなのだけど面倒なのでとりあえず日本語です。
-   `master` に入らないとビルドされないので、内容はとりあえず https://github.com/kmyk/online-judge-tools/blob/docs/ci/docs/run-ci-on-your-library.rst から確認してください。

NONE: add docs/run-ci-on-your-library.rst

---

docs/run-ci-on-your-library.rst

ちょっとだけ修正です。
`./test.sh` だと実行可能フラグ立てないとだめなのでユーザに優しくない。しかし実行可能フラグの概念の説明をするのもしんどい。なので単に `bash test.sh` に修正します。

NONE: replace "./test.sh" with "bash test.sh" in docs/run-ci-on-your-library.rst

---

readme.md
setup.cfg
setup.py

`setup.cfg` は新しめ (といっても数年前) の `setuptools` を要求してしまう問題があります。しかたがないので最低限の部分だけを `setup.py` に書き戻します。

NONE: make it possible to install with old setuptools

---

CHANGELOG.md
onlinejudge/__about__.py

一瞬誤ってv6.6.1タグをpushしてしまいましたが、大丈夫なはずです(汗)。
pypiに一度アップロードされるともう修正できないですが(削除はできる)、pypiコケたのでいけるはず。

RELEASE: 6.6.1

---

onlinejudge/dispatch.py
onlinejudge/service/anarchygolf.py
onlinejudge/service/aoj.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/facebook.py
onlinejudge/service/hackerrank.py
onlinejudge/service/kattis.py
onlinejudge/service/poj.py
onlinejudge/service/topcoder.py
onlinejudge/service/toph.py
onlinejudge/service/yukicoder.py
onlinejudge/type.py
tests/service_atcoder.py
tests/service_topcoder.py

#464 
放置すると拡大してしまう系の設計ミスなのではやめに修正します。
#461 とかが上手くいくようになるはずです。
(大規模な破壊的変更なので他のプルリクを巻き込んで衝突しないように `develop` branch に向けてのプルリクにしてあります)

#464: breaking changes

---

tests/command_generate_output.py
tests/command_test.py

Windows 環境上での並列実行の問題 #468 がありましたが、やっぱりまだときどき落ちるので対策します。

#468: reduce the number of jobs on tests of -j options

---

tests/command_download_poj.py

http://poj.org/ はよく落ちるのですが、これが落ちてる間ずっと CI も落ちてしまうのは適切ではありません。これをなんとかします。

NONE: skip tests for POJ if poj.org is down

---

onlinejudge/service/codeforces.py
tests/service_codeforces.py

close #435
こどふぉのコンテストや問題の列挙をできるようにします
(プルリクの宛先は `develop` です)

#435: add onlinejudge.service.codeforces.CodeforcesContest and some methods

---

onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/type.py
tests/service_atcoder.py
tests/service_codeforces.py

#484 で議論した内容にそって refactoring をしました。
やったことは以下の 2 点のみです。
1.  `Content` から `Data` に名前を変更
1.  `NamedTuple` で代用してたところを class にする
@fukatani 巨大になってしまって申し訳ないですが、レビューよろしくお願いします :pray:
これが終わったらバージョンを上げる予定です。
(宛先は `develop`)

#484: refactoring

---

onlinejudge/_implementation/command/generate_input.py
onlinejudge/_implementation/main.py
onlinejudge/_implementation/utils.py
readme.md
tests/command_generate_input.py
tests/utils.py

ランダムケースを生成するときに使うサブコマンドを追加します。
たとえば、ランダムケースを生成するスクリプトと、愚直解と、バグってる実装とを与えると、いい感じに撃墜ケースを生成してくれます。
この機能それ自体にさほど価値はありません。多少便利にはなりますが、同等のことは `or i in {000..099} ; do ./generate.py > test/random-$i.in ; done` とか `seq 100 | parallel './generate.py | tee test/random-{}.in | ./a.out > test/random-{}.out'` などでできて、ほぼ困らないためです。
これはむしろドキュメントとして働かせることを意図しています。「ランダムケースを生成してテストをする」という発想をまだ持っていない競プロerはおそらく多いはずですが、具体的にサブコマンドとして提供することでこの発想を自然に導入できます。
(宛先は `develop`)

NONE: add generate-input command

---

onlinejudge/service/atcoder.py

AtCoder のページは日本語の問題文と英語の問題文を両方持っていて、片方を不可視 (HTML 的には存在する) にしています。サンプルもそれに応じてすべて 2 回ずつ出現しています。
これに関連しての警告のようなメッセージを出力していたのですが、どうにも邪魔な気がするため消しておきます。

NONE: supress a noisy log of parsing samples of AtCoder

---

onlinejudge/_implementation/main.py
onlinejudge/_implementation/testcase_zipper.py
onlinejudge/type.py
tests/command_download_atcoder.py

Resolve #413 
413で例外を投げるようにしました。
エラーメッセージがわかるようなわからないような感じだったので、サンプルのパースに失敗したことをメッセージ煮だすようにしました。
また、従来、中途半端にsample.in/outが残っていましたが、怪しいのでなにも残さないようにしてみました。

Raise error if sample parse failed.

---

onlinejudge/_implementation/command/login.py

close #514 
もともと例外を catch することでウィンドウが閉じられたことを確認していましたが、 Windows 環境下では飛ぶ例外の種類が異なるようです。最も広く受けられる例外クラスを指定すれば解決するので、そのようにします。

#514: fix a problem of WebDriver on Windows

---

tests/command_download_yukicoder.py
tests/command_login.py
tests/command_submit.py
tests/service_topcoder.py
tests/utils.py

close #515 
ログインが必要なテストはログイン済みの場合にのみ実行するようにします。これでローカルでもテストは常に成功するようになります。

#515: make "python3 steup.py test" always succeed

---

onlinejudge/_implementation/command/submit.py
onlinejudge/_implementation/main.py

close #519
`sensible-browser` command とかのあたりを頑張って叩いていたのをやめ、`webbrowser` module を使います。コードが簡潔になり、かつ、WIndows 環境への可搬性が向上します。
-   `--open-browser` option を削除する破壊的変更が含まれています。
-   ブラウザを新規に起動する形になってしまったときに `oj` のプロセスをブロックしてしまう問題 (仕様) はそのままです。

#519: use webbrowser module instead of sensible-browser command

---

CONTRIBUTING.md

pytest時間かかるかもなので、これはこれで入れます。
シンプルに消しました。
上で言うとおりformatterをかけてくれれば、ローカルでチェックする必要はないと思うので。
(チェックコマンドを叩くくらいなら、formatterを叩くべき。)

None: fix contributing.

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

これで`test.py`の入れてない重要な分岐はなくなるはず、、
残りは例外やログ表示など。入れないところもありますし後回しでいいでしょう。

Increase command test coverage.

---

.travis.yml

カバレッジのレポートはcoverallsに出力してもらうので、テストレポートからは消すことにします。

None: simplify test report.

---

onlinejudge/service/yukicoder.py
tests/service_yukicoder.py

In [no.750](https://yukicoder.me/problems/no/750) and [no.751](https://yukicoder.me/problems/no/751), the author have written sample case using `<br>` tag within `<pre>` tag, which is not a user concern but we might not have been expected.
<br>
For example,  [no.750](https://yukicoder.me/problems/no/750) サンプル1 入力1
`<pre>6<br />1 1<br />7 4<br />0 5<br />1 3<br />-8 9<br />5 1</pre>`
is given for online-judge-tools.
<br>
[Beautiful Soup documents](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#string) says that
> If a tag contains more than one thing, then it’s not clear what `.string` should refer to, so `.string` is defined to be `None`:
<br>
So we should fix
`s = tag.string or ''  # tag.string for the tag "<pre></pre>" returns None`
(in `_parse_sample_tag` function, …

solve issue/192 (the case when <br> tag exists within <pre> tag)

---

onlinejudge/service/atcoder.py
tests/command_download_atcoder.py

This is the continuation of #513
I fixed my modification to pass the tests, and added a testcase.

Handle empty testcases for AtCoder (e.g. AGC036 B)

---

setup.cfg

Resolve #535 .
For build stability, these library version should be pinned.
But we should not forget update them regularly.
Especially, many of `mypy` updates are helpful for finding bugs.

#535: Pinning version of linter libraries.

---

tests/service_codeforces.py

Codeforces.list_problemsがカバーされてないので。
大は小を兼ねる感もあり、list_problems_dataは重複感がありますが、そこまでテスト時間にも関わらないので一応そのままにします。

#538: Test codeforces.list_problems

---

onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/type.py

https://github.com/python/mypy/issues/2984
のjukkaLさんの発言を元に修正。
結局immutableなコレクションだったらいいようで、`Sequence[SubClass]`だったら通ります。
疑問
- Sequence[Problem]といいつつ実装でリストを返してもmypyがエラーを発しない。(mypyの限界？)
- なんでimmutableなコレクションだったら問題ないのかよくわかってない(私の理解力の問題)。
とはいえ、mypyのコラボレーターが言ってることだし、immutableであればいいということでタプルを返すようにしました。
他にもListを返している関数がありますが、それの要素は継承関係がないしということでそのままにしています。
また、`list_problems`という関数名もひとまずそのままにしています。

None: type of fix list_problems.

---

onlinejudge/_implementation/utils.py
onlinejudge/service/yukicoder.py
tests/implementation_utils.py
tests/service_yukicoder.py
tests/utils.py

In #553, I described our tools couldn't parse sample cases such as `<pre><strong>3<br/>1</strong> 2<br/>3 4<br/>5 6</pre>` correctly. In this pull request, I try to solve this problem.
<br/>
<br/>
Let me introduce the image above.
The image above is a rooted tree which root is a sample (input || output) we want to treat correctly.
In this image, each node is painted by type.
- red ... `bs4.Tag`
- blue ... `bs4.NavigableString`
The root type is always `bs4.Tag` (because every input for online-judge-tools is surrounded by`<pre></pre>`).  
`bs4.Tag` has attribute `.contents` (`bs4.NavigableString` and `bs4.Comment` doesn't).
If we use `.contents` to variable which type is `bs4.Tag`, then we get `list` which elements' type is `bs4.Tag` or `bs4.NavigableString` or `bs4.Comment`.
(`<br/>` type …

#553: fix the parsing problem in <pre> tag

---

CHANGELOG.md

`CHANGELOG.md` に漏れていた変更やコントリビュータの名前を追加します。
まじめに見てなかったので見逃がしていました。ドキュメントの追加は CHANGELOG に乗せる価値があるものですし、コントリビュータの名前も書かれる必要があります。
特にコントリビュータの名前を乗せるのは重要です。それが readme に書き切れなくなったとしても CHANGELOG には書いていくべきです。誰がどの部分にどれだけ貢献したかの情報を明確にすることは OSS 開発にとって重要です。
詳細については https://producingoss.com/ja/credit.html や https://keepachangelog.com/ja/1.0.0/#why を読んでみてください。

fix CHANGELOG.md with adding contributors' names

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/main.py
tests/command_download.py
tests/command_download_invalid.py

- remove `--overwrite` option
- abort `download` if file already exists.
- raise InvalidURL if contest is not supported. (Sorry, this feature can be split to other PR)

[breaking consistency] Unsupport --overwrite option and abort download if file already exists.

---

readme.md

close #574
This solves the problem described at https://github.com/kmyk/online-judge-tools/issues/570#issuecomment-545461688 using [sourcerer-io/hall-of-fame](https://github.com/sourcerer-io/hall-of-fame), #574.
Though the hall-of-fame doesn't work as the full list of contributors, but it's Okay. I think that a list on `readme.md` is one to encourage (potential / current) contributors rather than as the full history of contributors. In terms of this, sourcerer-io/hall-of-fame is better than a simple list of names.

use sourcerer-io/hall-of-fame

---

onlinejudge/type.py

Abstact methodなので、NotImplementErrorを投げるのが正しい気がします。

raise Not Implement Error from abstract method.

---

tests/dispatch.py

I found `assertIsInstance` method and we should use it rather than `assertTrue(isinstance(...))`.
`assertIsInstance` is more readable and its message is nicer. It displays actual type when tests are failed.

Use assertIsInstance method.

---

onlinejudge/_implementation/utils.py
onlinejudge/dispatch.py
onlinejudge/service/atcoder.py
onlinejudge/type.py
tests/dispatch.py
tests/type.py

Currently, no contests support `get_problem`. So we should use `download_problem` rather than `get_problem`.
And I found `get_problem` can't be supported for most contest. I investigated AtCoder, yukicoder and Codeforces.
Once we unsupport `get_problem`. If we need it in the future, we can re-implement it.

[breaking minor API] replace get_problem of submissions with download_problem

---

onlinejudge/_implementation/command/submit.py

Hi! Thank you for providing the great OSS!
I am using online-judge-tools and it helps me a lot, but there is a little bit problem for me.
The code submission in macOS seems to be broken.
I just fixed the problem, so I am glad if you review the code.
When I submit the code with `oj` command, the error message like the following is shown every time:
```bash
$ oj submit https://atcoder.jp/contests/abc134/tasks/abc134_a main.cc
[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/abc134/tasks/abc134_a'): https://atcoder.jp/contests/abc134/tasks/abc134_a
[*] code (205 byte):
...
[x] sleep(3.00)
Are you sure? Please type "abca" abca
...
[x] 200 OK
[+] success: result: https://atcoder.jp/contests/abc134/submissions/8221095
File …
```

fix issue for opening browser in OSX

---

CHANGELOG.md

マークアップの細かい修正です。気付いてしまったので直しておきます。
-   Markdown の見出し行は、 `#` がひとつだと HTML の `<h1>` に相当するものとして扱われ、`##` とふたつ書くと `<h2>` 相当として扱われます。`##` の方が適切な箇所で `#` が使われてたので修正します
-   具体的な処理系の名前は挙げられないんですが、見出し行の後には空行を空けておいた方が可搬性の意味で無難な感じがあります

fix the markup of CHANGELOG.md

---

onlinejudge/service/codeforces.py

Related to: #573 
In this PR,
- Apply parse_content to Codeforces.
- Fix assert logic in `onlinejudge/service/codeforces.py`.

Apply parse_content to Codeforces

---

onlinejudge/_implementation/utils.py

fix #609, reported by @yosupo06
`fallback` を指定すれば直るらしいので指定します。実際の環境で試してないですが、 `shutil.py` を読む限りではこれで直るはずです。
https://docs.python.org/ja/3/library/shutil.html#shutil.get_terminal_size

fix a bug of logging on terminals whose size is unknown

---

onlinejudge/service/atcoder.py

https://atcoder.jp/contests/practice の問題を見たり提出をしたりするには「参加ボタン」を押す必要があるが、これを押してない人が `is_logged_in` 関数に触れると 404 するらしい (再現が難しすぎて確認はしていません)。これを直します。

avoid the AtCoder practice contest since it requires registration

---

onlinejudge/service/atcoder.py
tests/command_download_atcoder.py

close #618 
次をします:
- `if` `elif` `elif` の構造から単一の `for の構造へ変更する
- #618 のためのテストを足す
- (ついでに) コメントを足しておく
#618 の原因は `h3+pre.prettyprint` であるのに `h3+section pre` のための分岐に食われてしまって `h3` のために違う場所を探していたためだったようです。
同様の理由で `h3+pre.literal-block` なども (もしあれば) 検出に失敗します。
---
実装ですが、大きく構造を変えるのが楽なのでそうしました。
ついでに  `tag_plus` がよくない (無闇に `yield` してるのとか外側の変数 `pre` を読んでるのとか) も修正されました。バグ修正のついでの refactoring はよくないのですが、書き直しが多いので巻き込みました。
ところで、単なる `h3+section>pre` を足すと `<h3>Sample Output 1</h3><section><pre>13</pre>構成できる文字列は<pre><code>abc</code></pre>や……` で誤検出になります。これは意図的に回避しています。
(修正量が大きくて嫌な感じがしますが、元がまずかったのでしかたないやつだと思っています)

rewrite _find_sample_tags of AtCoder

---

onlinejudge/_implementation/testcase_zipper.py
tests/command_download_atcoder.py

fix #615 
サンプルの解析の際に `<h3>Sample Input 2</h3>` みたいなところを見て警告を出しているのですが、これを警告でなくエラーにします。
#615 の例を完全に解析しきるのは無理 (できたとしても HTML parser の実装に強く依存してしまうのでどうせすぐ壊れる) ですので、これは諦めます。しかし、まずいのはエラーにならず正常終了してしまうことなので、このプルリクによって #615 が解決されます。

throw exceptions if the titles of sample cases are abnormal

---

docs/run-ci-on-your-library.en.rst

「`.test.cpp` という拡張子を持つファイル」と「`test.cpp` のような名前のファイル」は異なりますが、翻訳の際に入れ替わってたようなので修正します。

Fix run-ci-on-your-library.en.rst

---

onlinejudge/service/library_checker.py

judge.yosupo.jp は常に `checker.cpp` を用いた special judge 形式になっています (https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-558599240) が、この `checker.cpp` を取得できるようにします。
オプションとか別コマンドとかを作るとなると仕様を検討したくなってしまう (「yukicoder も special judge がありますが……」など) ので、とりあえず内部メソッドだけにしておきます。
たとえば `python3 -c 'import onlinejudge, sys ; sys.stdout.buffer.write(onlinejudge.dispatch.problem_from_url("https://judge.yosupo.jp/problem/unionfind").download_checker_cpp())'`  などとします。
---
- できれば 7.4.0 に一緒に入ってくれるとうれしい
- 用途は https://github.com/kmyk/online-judge-verify-helper/issues/19 です
- cc @yosupo06 @beet-aizu

add an internal method LibraryCheckerProblem.download_checker_cpp()

---

onlinejudge/service/atcoder.py
tests/command_download_atcoder.py
tests/service_atcoder.py

-   fix https://github.com/kmyk/online-judge-tools/issues/625
-   replace `h3+section>pre.prettyprint` with `h3+section>pre:first-child`
単に `.prettyprint` の指定を消すと https://github.com/kmyk/online-judge-tools/issues/625#issuecomment-560944228 の問題があります。なので `:first-child` の制約で置き換えました。

update a pattern to list samples in AtCoder

---

onlinejudge/service/aoj.py
tests/service_aoj.py

fix https://github.com/kmyk/online-judge-tools/issues/207
AOJ はサンプルケース一覧の API を持ちますが、対応状況が微妙です。手動登録かつHTMLと別管理なためでしょう。対策として、API に登録されていなかったら HTML 手動パースするようにします。

parse HTML of AOJ problems when samples not registered in API

---

onlinejudge/_implementation/command/download.py
tests/command_download_invalid.py
tests/command_download_kattis.py

When user use `download`, they expect any samples will be downloaded.
That means, if no samples are downloaded, it is unexpected behavior.
It is user friendly, `oj` shows error occurred explicitly.
```
$ oj d https://tdpc.contest.atcoder.jp/tasks/tdpc_contest
[x] GET: https://pypi.org/pypi/online-judge-tools/json
[x] 200 OK
[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/tdpc/tasks/tdpc_contest'): https://tdpc.contest.atcoder.jp/tasks/tdpc_contest
[x] load cookie from: /home/ryo/.local/share/online-judge-tools/cookie.jar
[x] GET: https://atcoder.jp/contests/tdpc/tasks/tdpc_contest
[x] 200 OK
[x] save cookie to: /home/ryo/.local/share/online-judge-tools/cookie.jar
[ERROR] Failed to parse sample.
```

Raises error if no sample found.

---

tests/command_submit.py

#626 の修正により`FAILED`になったtestを発見したので修正します。
(Travisでは`SKIPPED`で通過していました)
<br>
修正1
```python3
tests.utils.run(['dl', url], check=False)
```
`False`にすることで(sampleが無いときに発生する)エラーを無視します。
<br>
修正2
```python3
tests.utils.run(['s', '-y', '--no-open', url, 'a.cpp'], check=True)
```
`url`の推論に失敗しているので、陽に指定します。

Fix command_submit.py

---

docs/onlinejudge.rst
docs/onlinejudge.utils.rst
onlinejudge/_implementation/download_history.py
onlinejudge/_implementation/utils.py
onlinejudge/service/atcoder.py
onlinejudge/service/library_checker.py
onlinejudge/utils.py

https://github.com/kmyk/online-judge-tools/issues/480#issuecomment-565946620 
`onlinejudge._implementation.utils` のなかからいくつか `onlinejudge.utils` に移した
-   `get_default_session` `with_cookiejar`
-   `default_cookie_path` なども移した (`with_cookiejar` した結果から取れちゃうし、いっしょにあると便利だろうので)
-   関数名はとりあえずそのまま、module の名前は `onlinejudge.session` という手もあるが細かく切るよりひとつにまとめた方がなんとなく楽かな、ぐらいの気持ちです。より良いのが思い付いたら提案してください
@yosupo06 これはあなたの目的のためによさそうですか？ ところで atcoder-tools 並に高機能でかつ AtCoder 以外にも対応してるラッパーはほしいので、期待しています

provide functions about sessions as a library

---

onlinejudge/_implementation/utils.py
onlinejudge/service/library_checker.py

2点です
- `problem.download_system_cases()` のたびに `git pull` してたけど最初の 1 回だけにする (速くなるのでうれしい)
- `~/.cache/online-judge-tools/library-checker-problems` に毎回 `cd` してたけどしないようにする (途中で Ctrl-C を押されたときの安定性とかがうれしい)

Library Checker に関連する改善

---

onlinejudge/service/codeforces.py
tests/service_codeforces.py

こどふぉの負荷対策の http://m1.codeforces.com/ のような URL を認識するようにします。
ただし内部のリクエストはすべて https://codeforces.com/ のままです。これはすこし混乱を招く仕様ですが http://m1.codeforces.com/ などは微妙に仕様が違ってて対応が無理なので仕方ないと考えています。

allow {m1,m2,m3}.codeforces.com as URL

---

tests/command_download_invalid.py

Unfortunately, I mistook again.
I verified test class name by `grep` command and other class names are right.

fix broken test name

---

onlinejudge/service/library_checker.py
tests/service_library_checker.py

`git pull` をするときにオプションの指定を間違えてて Library Checker 対応が壊れていました。
これを修正し、テストを足しました。
参考: https://this.aereal.org/entry/2014/05/19/192043

Fix a bug of git pull about Library Checker

---

onlinejudge/_implementation/main.py
onlinejudge/service/__init__.py
onlinejudge/service/codechef.py
readme.md
tests/service_codechef.py

close #650 
- I couldn't find a proper way to detect the tag which contains the problem statement.
- The format of sample sections of CodeChef has surprising diversity. All of them are used: HTML with pre tags, Markdown with code fences, Markdown with indented code blocks, etc.. I've abandoned supporting all of them. Only Markdown is supported.
- The Markdown is parsed by hand, because I don't like to add a new dependency only for this.
予想よりかなり面倒だったのでほどほどの完成度で諦めています。動かないケースもあるけどある程度は動くし他の機能には何も悪影響がないので、少なくとも確実に正の価値はあると思っています。

add CodeChef support

---

setup.py

`pip install -U online-judge-tools` ってして Python 2.x のライブラリ扱いでインストールされてしまって動かなくて困るやつをやったことはありませんか？ 私はわりとやるのでこれを対策します。

Use python_requires='>=3.5' in setup.py

---

onlinejudge/_implementation/command/submit.py

Newly added:
- `Ceylon`        -> `.ceylon`
- `Crystal`        -> `.cr`
- `Julia`            -> `.jl`
- `Kotlin`          -> `.kt`, `.kts`
- `Moonscript` ->   `.moon`
- `Nim`            ->    `.nim`
- `Unlambda`  ->    `.unl`
- `Visual basic` ->  `.vb`
And added to `Common Lisp`:
- `Common Lisp` -> `.lisp`, `.lsp`, `.cl`
Please confirm...

Add extensions and fix small typo

---

CHANGELOG.md
onlinejudge/__about__.py

バージョンを上げます。
いまあるプルリクはマージまでしばらくかかりそうなこと、すでにマージされたプルリクの反映をはやめにしておきたいことが理由です。

RELEASE: 7.8.0

---

onlinejudge/service/library_checker.py

Library Checker 本体の更新に合わせて以下をします:
- `python3 generate.py path/to/info.toml` 形式を使う
- `--compile-checker` も叩けるようにする (微妙に破壊的変更になってる)
- (ついでに) 標準出力に吐いてたいくつかを標準エラー出力に切り替え
注意として、`toml` package への依存は残します (Library Checker 側では使うので)
cc: @yosupo06
--
~~ただし現在は https://github.com/yosupo06/library-checker-problems/issues/268 の問題により CI 通りません~~

Library Checker の更新に追従

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

expectedの後ろのスペース埋めをやめました。
テストケースを作るときにスペースを数えるのに消耗しているため。
見た目は変わりません。

test: remove unneccesary padding.

---

tests/service_yukicoder.py

Test about yukicoder sometimes fails because of unexpected re-judged status sentence.
(This screenshot was taken in [Travis CI Job #1445.1](https://travis-ci.org/kmyk/online-judge-tools/jobs/649196499?utm_medium=notification&utm_source=github_status).)

Fix test to deal with re-judge

---

onlinejudge/_implementation/command/test.py
tests/command_test.py
tests/utils.py

snipped side by side if output is long.

---

onlinejudge/_implementation/command/test.py
tests/command_test.py

side-by-sideモードで省略された行がある時、後ろが何行省略されたか表示するようにしました。
(outputとexpectで微妙に違うが、outputの行数基準)
前の行も省略されることがありますが、行番号書いてあるので大丈夫でしょう。
#684

side-by-side-diff: display number of snipped lines.

---

onlinejudge/_implementation/command/submit.py
onlinejudge/_implementation/main.py

fix #690 
Python コードの提出の際にあった以下の問題を解決します
1. もはや Python 2 は使われてないのに Python 3 の指定が要求される
2.  PyPy を指定するオプションがバグってて機能してない

Improve submitting Python code

---

onlinejudge/_implementation/command/download.py
onlinejudge/_implementation/command/generate_input.py
onlinejudge/_implementation/command/generate_output.py
onlinejudge/_implementation/command/submit.py
onlinejudge/_implementation/command/test.py
onlinejudge/_implementation/logging.py
onlinejudge/_implementation/utils.py
tests/command_test.py

fix #698 
cc @azarashi2931
末尾空白が見えるようにします。
行末尾空白を AC にはできません。最近の AtCoder では多少の空白はあっても AC になるけど、古い問題だとそうとは限らないためです。ちなみに、ファイル末尾空白は許されるより場合が多いので AC になってるけど、これも実は怪しい挙動です。

Coloroize trailing spaces

---

onlinejudge/_implementation/command/test.py
tests/command_test.py
tests/utils.py

fix #685 
やりました。
実装が汚いけど、もっと賢い方法でやるとコードが膨らんでむしろ汚くなるのでまだ愚直にやります。同様のパターンが他にももうひとつふたつ増えたら対応します。

Allow CRLF

---

onlinejudge/_implementation/command/submit.py
tests/implementation_language_guessing.py

AtCoder の言語更新で Python コードの提出言語判定が壊れたので修正します。
https://atcoder.jp/contests/judge-update-202004
もともと微妙にバグってたのが、`Python (3.8.2)` が部分文字列として `3` と `2` を含むので Python 3 かつ Python 2 の判定になって顕在化しました。

Fix the bug of submit subcommand about Python and AtCoder's language update

---

onlinejudge/_implementation/main.py

Replaced 2 instances of "form" with "from" in the command line help message (`oj -h`).

fix typos in command line help message

---

onlinejudge/service/atcoder.py

This PR fixes a parse error when parsing available languages from AtCoder submit pages.
When I tried to submit my code to AtCoder, I faced the following error today.
```bash
$ oj -v s https://atcoder.jp/contests/abc055/tasks/abc055_b main.cpp
...
File "/Users/kazuhiroserizawa/.pyenv/versions/3.8.0/lib/python3.8/site-packages/onlinejudge/_implementation/main.py", line 233, in main
run_program(namespace, parser=parser)
File "/Users/kazuhiroserizawa/.pyenv/versions/3.8.0/lib/python3.8/site-packages/onlinejudge/_implementation/main.py", line 212, in run_program
submit(args)
File "/Users/kazuhiroserizawa/.pyenv/versions/3.8.0/lib/python3.8/site-packages/onlinejudge/_implementation/command/submit.py", line 56, in submit
language_dict = {language.id: …
```

Skip language option tags without `value` at AtCoder

---

onlinejudge/service/aoj.py
tests/command_download_aoj.py

#737 
https://onlinejudge.u-aizu.ac.jp/problems/{problem_id}
という形のURLを認識できるように変更しました。
あまり慣れていないのですが、プルリクこんな感じで大丈夫でしょうか…？

Support new URL of AOJ

---

README.md
onlinejudge_command/download_history.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/submit.py
tests/command_submit.py

Clear the downloading history when test/ directory is empty

---

onlinejudge_command/download_history.py
onlinejudge_command/main.py
onlinejudge_command/subcommand/download.py
onlinejudge_command/subcommand/login.py
onlinejudge_command/subcommand/submit.py
onlinejudge_command/update_checking.py
onlinejudge_command/utils.py
tests/command_download.py
tests/command_download_invalid.py
tests/command_login.py
tests/command_submit.py
tests/implementation_language_guessing.py

see https://github.com/online-judge-tools/oj/issues/755#issuecomment-623118672
It has passed enough time from the version 10.0.0 and the effect of
the conflict becomes little. It's time to remove this workaround.

Remove a workaround for the conflict of the name of the modules

---

onlinejudge_command/subcommand/submit.py
onlinejudge_command/utils.py

fix https://github.com/online-judge-tools/oj/issues/773
このプルリクは、WSL 内で `oj s` するとウェブブラウザが起動してくれない問題を修正します。
Windows 環境がないのでテストができていません。以下 2 点を誰かが手動で確認して報告してくれたらマージします。
- 環境変数 `BROWSER` を設定しない状態で WSL 内側で `oj s` をすると Windows 側で何らかのウェブブラウザが起動する
- 環境変数 `BROWSER` を設定した状態で WSL 内側で `oj s` をすると Windows 側で `BROWSER` で指定したものと同じウェブブラウザが起動する
よろしくお願いします。

Use explorer.exe on WSL

---

onlinejudge_command/subcommand/generate_input.py
tests/command_generate_input.py

#806 を確認してたら気付けた
関数に型ヒントがないとその内部の型検査が省略されてしまうんですが、「mypy さんは良いっていってるし動くでしょ」をしてるとこういうところでやられる。
あとそもそもテストを書いてないのがだめ。コーナーケースでもきっちり書きましょう。

Fix the bug of generate-input subcommand which happens when generatrs failed

---

onlinejudge_command/main.py
onlinejudge_command/output_comparators.py
onlinejudge_command/subcommand/test.py
tests/command_test.py

close https://github.com/online-judge-tools/oj/issues/774 https://github.com/online-judge-tools/oj/issues/810
related https://github.com/online-judge-tools/oj/issues/776
For the `test` subcommand,
-   the default behavior of comparing is updated
-   options are updated
-   rename `-m` option to `-M` option
-   rename `--side-by-side` `-S` option to `--diff` `-D` option
-   remove `--rstrip` `--no-rstrip` options
-   add `--compare-mode` `--ignore-spaces` `--ignore-spaces-and-newlines` options
-   add `--display-mode` option

[breaking changes] Modify the ways of comparing outputs in `test` subcommand

---

onlinejudge_command/main.py
onlinejudge_command/utils.py

わりと以下のような混乱が生じてるぽいので、破壊的変更ついでに
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">online-judge-toolsをコマンドプロンプトを使って実行しようとしました。しかし、警告やエラーが起きて正常に実行出来なかったのですが、どのように改善すれば良いでしょうか？<a href="https://twitter.com/hashtag/%E7%AB%B6%E3%83%97%E3%83%AD?src=hash&amp;ref_src=twsrc%5Etfw">#競プロ</a> <a href="https://twitter.com/hashtag/AtCoder?src=hash&amp;ref_src=twsrc%5Etfw">#AtCoder</a> <a href="https://t.co/tuQ0aTvBZd">pic.twitter.com/tuQ0aTvBZd</a></p>&mdash; Leo (@Leo80417411) <a href="https://twitter.com/Leo80417411/status/1303232798719791104?ref_src=twsrc%5Etfw">September 8, 2020</a></blockquote>

For `test` subcommand, use `.\a.exe` instead of `./a.out` for the default command on Windows

---

CHANGELOG.md
onlinejudge_command/__about__.py

変更が大きいのでしばらく merge はせず様子見が必要そう
気分次第だけど、Python 3.5 の EOL の 2020-09-13 ぐらいまで待つかも

RELEASE: 11.0.0

---

.github/workflows/format.yml
onlinejudge_command/main.py
onlinejudge_command/subcommand/generate_input.py

close https://github.com/online-judge-tools/oj/issues/832

Make --hack option of generate-input subcommand more user-friendly

---

onlinejudge_command/main.py

#836 に対応しました。  
具体的には
* `if not is_updated` の際に  
"Please run: $ pip3 install -U online-judge-tools online-judge-api-client" を加えて表示するようにしました。  
至らないところなどがあればぜひご指摘お願いします。

アップデートがなされていない際に表示するメッセージの追加

---

onlinejudge_command/utils.py

Show a hint message when cookie.jar is broken

---

onlinejudge_command/main.py

Hi, this is a tiny fix of the old read-the-docs link in the help text.
Thank you for creating a useful tool! 🙂

Fix the old link in the help text

---

onlinejudge_command/main.py

I overlooked this in #854. Putting the anchor makes it more helpful for users.

Put the anchor to the link in the help text

---

onlinejudge_command/main.py

チュートリアルへのリンクをもっとたくさん張っておくとよい気がする。特に `$ oj --help` だけから辿り着けるようになっていてほしい

Add more links to the tutorial from the help text

---

onlinejudge_command/subcommand/test.py

次を参考にして実装しました:
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">プルリクというか、一応私のmacでは普通にgnu time動いていて、ただ単に「time」じゃなくて「gtime」というコマンド名なので --gnu-time gtime をつけることで特になんの問題もなくwarning 消えました</p>&mdash; あやせひろみ (@hiromi_ayase) <a href="https://twitter.com/hiromi_ayase/status/1380451290103181313?ref_src=twsrc%5Etfw">April 9, 2021</a></blockquote>

Use "gtime" for GNU time on macOS

---

onlinejudge_command/subcommand/download.py

stack trace がでると不安になるし「ログインが必要」というのが分かりにくい

Improve error messages for HTTP errors on `oj download`

---

onlinejudge_command/update_checking.py
setup.py

Fix #923
distutils でバージョンをパースしてる箇所は packaging に代替するのが世の流れらしいです。

Remove distutils
